version: '3.3'
services:
    stardog:
        image: stardog/stardog:latest
        hostname: stardog
        container_name: stardog
        ports:
            - 5820:5820
        volumes:
            - ./stardog-home/:/var/opt/stardog
        environment:
            - STARDOG_SERVER_JAVA_ARGS="-Xmx8g -Xms8g -XX:MaxDirectMemorySize=16g"
    stardog-studio:
        image: stardog/stardog-studio:current
        hostname: stardog-studio
        container_name: stardog-studio
        ports:
            - 8888:8080
    
        